---
- name: "Add Node.js from Nodesource main 1"
  become: true
  shell: |
    # curl --silent --location https://deb.nodesource.com/setup_13.x | sudo -E bash -
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt install -y nodejs
    sudo npm install -g n
    sudo n 13.8.0


- name: "Install Node.js 13"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cashe: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
